Expanding the UiS4ADL dataset used in Fadi et al. (2024) from 30 to 43 subjects.

In [1]:
import os
import warnings
import pandas as pd
import numpy as np

# Suppress warnings from Python and external libraries
os.environ["PYTHONWARNINGS"] = "ignore"  # Suppress Python warnings
warnings.filterwarnings("ignore")

In [2]:
fs = 100 # sampling frequency in Hz

In [3]:
# Loading the csv file with the old data
old_data = pd.read_csv("../Data/UiS4ADL/Raw/Old/UiS4ADL-100hz.csv")
print(old_data.head())

# Loading the csv file with the new data
new_data = pd.read_csv("../Data/UiS4ADL/Raw/New/all_data.csv")
print(new_data.head())

timestep = 10

   timestamp  accX[mg]  accY[mg]  accZ[mg]  gyroX[mdps]  gyroY[mdps]  \
0          0         0         0      1009          490          350
1         10        -1         1      1010          490          350
2         20         0         1      1011          420          280
3         30         0         1      1009          350          280
4         40         1         1      1010          420          280

   gyroZ[mdps]  magnX[mG]  magnY[mG]  magnZ[mG]  ...  fxGravityY[g]  \
0         -770       -289          4       -430  ...            0.0
1         -770       -279         10       -439  ...           -0.0
2         -770       -289          0       -435  ...           -0.0
3         -770       -286         12       -435  ...           -0.0
4         -840       -282          0       -438  ...            0.0

   fxGravityZ[g]  fxLinAccX[g]  fxLinAccY[g]  fxLinAccZ[g]  fxHeading[deg]  \
0           -1.0         0.001         0.000         0.009         181.065
1           -1.0         0.001         0.001         0.010         181.065
2           -1.0         0.001        -0.000         0.011         181.065
3           -1.0         0.001        -0.000         0.009         181.065
4           -1.0         0.001        -0.001         0.010         181.065

   adl  session  subject  fileID
0    0        1     1125       0
1    0        1     1125       0
2    0        1     1125       0
3    0        1     1125       0
4    0        1     1125       0

[5 rows x 28 columns]
     time[ms]  accX[mg]  accY[mg]  accZ[mg]  gyroX[mdps]  gyroY[mdps]  \
0  64221000.0      -5.0       2.0    1028.0        420.0       -210.0
1  64221000.0      -7.0       2.0    1024.0        420.0       -210.0
2  64221000.0      -7.0       2.0    1024.0        420.0       -210.0
3  64221000.0      -3.0       2.0    1030.0        350.0       -280.0
4  64221000.0      -9.0       0.0    1026.0        350.0       -280.0

   gyroZ[mdps]  magnX[mG]  magnY[mG]  magnZ[mG]  ...  fxLinAccX[g]  \
0       -630.0       32.0     -305.0        9.0  ...         0.000
1       -630.0       33.0     -317.0        8.0  ...         0.000
2       -630.0       11.0     -298.0       41.0  ...         0.000
3       -630.0       11.0     -298.0       41.0  ...         0.000
4       -560.0       24.0     -307.0        9.0  ...        -0.001

   fxLinAccY[g]  fxLinAccZ[g]  fxHeading[deg]  fxHeadError[deg]  \
0        -0.001         0.028          63.827             0.083
1         0.001         0.024          63.827             3.142
2         0.001         0.024          63.827             3.142
3        -0.003         0.030          63.827             3.142
4         0.002         0.026          63.827             0.074

   ElapsedTime[us]  adl  session  subject  fileID
0          12988.0    0        0     2275    3376
1            656.0    0        0     2275    3376
2            656.0    0        0     2275    3376
3            657.0    0        0     2275    3376
4          12867.0    0        0     2275    3376

[5 rows x 33 columns]

In [4]:
# Adding a new timestamp column to the new data
for fileID in sorted(new_data['fileID'].unique()):
    mask = new_data['fileID'] == fileID
    new_data.loc[mask, 'timestamp'] = np.arange(mask.sum()) * timestep
new_data

,time[ms],accX[mg],accY[mg],accZ[mg],gyroX[mdps],gyroY[mdps],gyroZ[mdps],magnX[mG],magnY[mG],magnZ[mG],...,fxLinAccY[g],fxLinAccZ[g],fxHeading[deg],fxHeadError[deg],ElapsedTime[us],adl,session,subject,fileID,timestamp
0,64221000.0,-5.0,2.0,1028.0,420.0,-210.0,-630.0,32.0,-305.0,9.0,...,-0.001,0.028,63.827,0.083,12988.0,0,0,2275,3376,0.0
1,64221000.0,-7.0,2.0,1024.0,420.0,-210.0,-630.0,33.0,-317.0,8.0,...,0.001,0.024,63.827,3.142,656.0,0,0,2275,3376,10.0
2,64221000.0,-7.0,2.0,1024.0,420.0,-210.0,-630.0,11.0,-298.0,41.0,...,0.001,0.024,63.827,3.142,656.0,0,0,2275,3376,20.0
3,64221000.0,-3.0,2.0,1030.0,350.0,-280.0,-630.0,11.0,-298.0,41.0,...,-0.003,0.030,63.827,3.142,657.0,0,0,2275,3376,30.0
4,64221000.0,-9.0,0.0,1026.0,350.0,-280.0,-560.0,24.0,-307.0,9.0,...,0.002,0.026,63.827,0.074,12867.0,0,0,2275,3376,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6677363,43075000.0,836.0,-412.0,47.0,10640.0,10570.0,2590.0,-14.0,-103.0,-87.0,...,0.050,-0.046,257.834,3.142,679.0,9,5,3245,4947,27730.0
6677364,43075000.0,827.0,-412.0,47.0,11760.0,10080.0,1610.0,-14.0,-103.0,-87.0,...,0.058,-0.049,257.704,3.142,681.0,9,5,3245,4947,27740.0
6677365,43075000.0,816.0,-409.0,45.0,12740.0,9520.0,560.0,-12.0,-106.0,-84.0,...,0.069,-0.054,257.563,3.142,680.0,9,5,3245,4947,27750.0
6677366,43075000.0,809.0,-410.0,42.0,13580.0,8820.0,-560.0,-17.0,-96.0,-84.0,...,0.077,-0.053,257.724,3.142,8565.0,9,5,3245,4947,27760.0
6677367,43075000.0,805.0,-411.0,39.0,14420.0,7980.0,-1750.0,-14.0,-100.0,-92.0,...,0.081,-0.058,257.568,3.142,679.0,9,5,3245,4947,27770.0

In [5]:
def concat_csv_with_metadata_and_files(df1_old, df2_new):
    try:
        # Keep only the columns in df2_new that are also in df1_old
        common_columns = [col for col in df2_new.columns if col in df1_old.columns]
        df2_new = df2_new[common_columns]

        # Concatenate the two DataFrames vertically
        combined_df = pd.concat([df1_old, df2_new], ignore_index=True)
        return combined_df

    except Exception as e:
        print(f"Error processing files: {e}")

df = concat_csv_with_metadata_and_files(old_data, new_data)
df

,timestamp,accX[mg],accY[mg],accZ[mg],gyroX[mdps],gyroY[mdps],gyroZ[mdps],magnX[mG],magnY[mG],magnZ[mG],...,fxGravityY[g],fxGravityZ[g],fxLinAccX[g],fxLinAccY[g],fxLinAccZ[g],fxHeading[deg],adl,session,subject,fileID
0,0.0,0.0,0.0,1009.0,490.0,350.0,-770.0,-289.0,4.0,-430.0,...,0.000,-1.000,0.001,0.000,0.009,181.065,0,1,1125,0
1,10.0,-1.0,1.0,1010.0,490.0,350.0,-770.0,-279.0,10.0,-439.0,...,-0.000,-1.000,0.001,0.001,0.010,181.065,0,1,1125,0
2,20.0,0.0,1.0,1011.0,420.0,280.0,-770.0,-289.0,0.0,-435.0,...,-0.000,-1.000,0.001,-0.000,0.011,181.065,0,1,1125,0
3,30.0,0.0,1.0,1009.0,350.0,280.0,-770.0,-286.0,12.0,-435.0,...,-0.000,-1.000,0.001,-0.000,0.009,181.065,0,1,1125,0
4,40.0,1.0,1.0,1010.0,420.0,280.0,-840.0,-282.0,0.0,-438.0,...,0.000,-1.000,0.001,-0.001,0.010,181.065,0,1,1125,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10559903,27730.0,836.0,-412.0,47.0,10640.0,10570.0,2590.0,-14.0,-103.0,-87.0,...,0.886,-0.093,0.043,0.050,-0.046,257.834,9,5,3245,4947
10559904,27740.0,827.0,-412.0,47.0,11760.0,10080.0,1610.0,-14.0,-103.0,-87.0,...,0.885,-0.096,0.043,0.058,-0.049,257.704,9,5,3245,4947
10559905,27750.0,816.0,-409.0,45.0,12740.0,9520.0,560.0,-12.0,-106.0,-84.0,...,0.885,-0.099,0.046,0.069,-0.054,257.563,9,5,3245,4947
10559906,27760.0,809.0,-410.0,42.0,13580.0,8820.0,-560.0,-17.0,-96.0,-84.0,...,0.886,-0.095,0.044,0.077,-0.053,257.724,9,5,3245,4947
10559907,27770.0,805.0,-411.0,39.0,14420.0,7980.0,-1750.0,-14.0,-100.0,-92.0,...,0.886,-0.097,0.043,0.081,-0.058,257.568,9,5,3245,4947

In [6]:
num_subjects = df['subject'].nunique()
print(f"Number of subjects after expansion: {num_subjects}")

Number of subjects after expansion: 43

## Save the combined dataset

In [7]:
 # Save the combined DataFrame to a new CSV file
output_file = f"../Data/UiS4ADL/Raw/UiS4ADL_{fs}hz_raw.csv"

# Remove the file if it already exists
if os.path.exists(output_file):
    os.remove(output_file)
    print(f"{output_file} has been removed successfully.")
else:
    print(f"{output_file} does not exist.")
    
# Save the combined DataFrame to a CSV file
df.to_csv(output_file, index=False)
print(f"The dataset was saved to {output_file}")

../Data/UiS4ADL/Raw/UiS4ADL_100hz_raw.csv does not exist.
The dataset was saved to ../Data/UiS4ADL/Raw/UiS4ADL_100hz_raw.csv